# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CoursesController < Casein::CaseinController
     before_filter :find_course,  :only => [:show, :update]
     before_filter :reify_course, :only => [:show]

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Courses'
  		@courses_all = Course.includes(:draft).order(sort_order(:name))

      @courses = @courses_all.map! { |course| course.draft.reify if course.draft? }

      @courses.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View course'
      # @course = Course.friendly.find params[:id]
      @photos = Photo.all
      @photo = Photo.new
    end
  
    def new
      @casein_page_title = 'Add a new course'
    	@course = Course.new
      @photo = @course.photos.build
    end

    def create
      @course = Course.new course_params
    
      if @course.draft_creation
        if params[:photos_attributes]
          params[:photos_attributes]['image'].each do |image|
            @photo = @course.photos.create(image: image)
          end
        end
        flash[:notice] = 'Course created'
        redirect_to casein_courses_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new course'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update course'
      
      @course.attributes = course_params
      
      if params[:publish]
        @course.draft_update
        @course.draft.publish!
        flash[:notice] = 'Course has been published'
        redirect_to casein_courses_path
      else
      if @course.draft_update
        flash[:notice] = 'Course has been updated'
        redirect_to casein_courses_path
      else
        flash.now[:warning] = 'There were problems when trying to update this course'
        render :action => :show
      end
      end
    end
 
    def destroy
      @course = Course.friendly.find params[:id]

      @course.photos.each do |photo|
        photo.update_attributes(imageable_id: nil, imageable_type: nil)
      end
      @course.draft_destroy
      flash[:notice] = 'Course has been deleted'
      redirect_to casein_courses_path
    end
  
    private

      def find_course
        @course = Course.friendly.find(params[:id])
      end

      def reify_course
        @course = @course.draft.reify if @course.draft?
      end
      
      def course_params
        params.require(:course).permit(:name, :description, photos_attributes: [:id, :caption, :course_id, :image])
      end

  end
end