# Scaffolding generated by Casein v5.1.1.5

module Casein
  class DashboardsController < Casein::CaseinController
    
    require 'google/api_client'
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Dashboards'


      client  = Google::APIClient.new

      client.authorization = Signet::OAuth2::Client.new(
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :audience             => 'https://accounts.google.com/o/oauth2/token',
        :scope                => 'https://www.googleapis.com/auth/analytics.readonly',
        :issuer               => ENV['client_email'],
        :signing_key          => Google::APIClient::PKCS12.load_key('config/API_Project_4fc819d124ee.p12', 'notasecret')
      ).tap { |auth| auth.fetch_access_token! }

      api_method = client.discovered_api('analytics','v3').data.ga.get


      # make queries
      @results = client.execute(:api_method => api_method, :parameters => {
        'ids'        => 'ga:45000190',
        'start-date' => Date.new(1970,1,1).to_s,
        'end-date'   => Date.today.to_s,
        'dimensions' => 'ga:pagePath',
        'metrics'    => 'ga:pageviews',
        'filters'    => 'ga:pagePath==/url/to/user'
      })

      # puts result.data.rows.inspect
    end
  
   
  
    private
      
      def dashboard_params
        params.require(:dashboard).permit(:index)
      end
  
  
  end
end
