# Scaffolding generated by Casein v5.1.1.5

module Casein
  class DashboardsController < Casein::CaseinController
    
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Dashboards'
    end
  
   
  
    private
      
      def dashboard_params
        params.require(:dashboard).permit(:index)
      end
  
  
  end
end
