# Scaffolding generated by Casein v5.1.1.5

module Casein
  class FormatsController < Casein::CaseinController
    before_filter :load_format, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Formats'
      @formats = Format.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View format'
      @photos = Photo.all
      @photo = Photo.new
    end
  
    def new
      @casein_page_title = 'Add a new format'
      @format = Format.new
      @photo = @course.photos.build
    end

    def create
      @format = Format.new format_params
    
      if @format.save

        if params[:photos_attributes]
            params[:photos_attributes]['image'].each do |image|
            @format.photos.create(image: image)
          end
        end

        flash[:notice] = 'Format created'
        redirect_to casein_formats_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new format'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update format'
    
      respond_to do |form|
        if @format.update_attributes format_params
          if params[:submit]
            @format.submit!
          elsif params[:approve]
            @format.approve!
          elsif params[:reject]
            @format.reject!
          elsif params[:publish]
            @format.publish!
          elsif params[:unpublish]
            @course.unpublish!            
          end
        
          form.html { redirect_to casein_format_path(@format), notice: "Format has been updated. #{undo_link}" }
          form.js
        else
          flash.now[:warning] = 'There were problems when trying to update this format'
          render :action => :show
        end
     end
    end
 
    def destroy
      @format.photos.each do |photo|
        photo.update_attributes(imageable_id: nil, imageable_type: nil)
      end
      @format.destroy
      flash[:notice] = 'Format has been deleted'
      redirect_to casein_formats_path
    end
  
    private
      
      def format_params
        params.require(:format).permit(:title, :workflow_state, :description, :published_at, :workflow_state, :whats_new, :when_from, :when_to, :venue, :address1, :address2, :city, :county, :country, :post_code, photos_attributes: [:id, :caption, :image])
      end

      def load_format
        @format ||= Format.friendly.find params[:id]
      end

      def undo_link
        view_context.link_to("undo", revert_version_path(@format.versions.last), :method => :post).html_safe
      end
  
  end
end
