# Scaffolding generated by Casein v5.1.1.5

module Casein
  class StaffsController < Casein::CaseinController
    before_filter :load_staff, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Staffs'
      @staffs = Staff.order(sort_order(:name)).paginate :page => params[:page]
    end

    def publish_index
      @casein_page_title = 'Staffs: Publish Index'
      @staffs = Staff.order(sort_order(:name))
    end
  
    def show
      @casein_page_title = 'View staff'
    end
  
    def new
      @casein_page_title = 'Add a new staff'
      @staff = Staff.new
      @photo = @staff.photo.build
    end

    def create
      @staff = Staff.new staff_params
    
      if @staff.save
        flash[:notice] = 'Staff created'
        redirect_to casein_staffs_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new staff'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update staff'
       respond_to do |format|
        
          if params[:submit]
            @staff.submit!
          elsif params[:approve]
            @staff.approve!
          elsif params[:reject]
            @staff.reject!
          elsif params[:publish]
            @staff.publish!
          elsif params[:unpublish]
            @staff.unpublish!
          end

        if @staff.update_attributes staff_params
        
          format.html { redirect_to casein_staff_path(@staff), notice: "Staff has been updated. #{undo_link}" }
          format.js
        else
          flash.now[:warning] = 'There were problems when trying to update this staff'
          render :action => :show
        end
     end
    end

    def update_multiple

      @staffs = Staff.where(id: staff_params[:staff_ids])

      @staffs.each do |staff|
        if params[:submit]
              staff.submit!
            elsif params[:approve]
              staff.approve!
            elsif params[:reject]
              staff.reject!
            elsif params[:publish]
              staff.publish!
        end
      end

      flash[:notice] = "Staffs have been updated"
      redirect_to publish_index_casein_staffs_path
    end
 
    def destroy

      @staff.destroy
      @staff.photo.destroy
      flash[:notice] = 'Staff has been deleted'
      redirect_to casein_staffs_path
    end
  
    private
      
      def staff_params
        params.require(:staff).permit(:name, { :staff_ids => [] }, :biography, :role, :photo, :published_at, :workflow_state, photo_attributes: [:id, :caption, :image, :_destroy])
      end

      def load_staff
        @staff ||= Staff.friendly.find params[:id]
      end

      def undo_link
        view_context.link_to("undo", revert_version_path(@staff.versions.last), :method => :post).html_safe
      end
  
  end
end
