client_id: 3MVG92u_V3UMpV.hdaH4EpiKBPi7wCzIVDIWlwmaIvzWA8N_bmQ1O4DUD8FDNzYqtplH0g082GmoV5skSAti1
client_secret: 335148879781836643
username: webdev@aims.uk.com.webdev
password: Greatadmin1b04YyPa0Qiv0CEgiVAUa8Yum
host: test.salesforce.com
debugging: true